---
# tasks file for nginx
- name: Install EPEL
  yum:
    name: epel-release
    update_cache: true
    state: latest
  when: ansible_distribution == 'CentOS'
  tags:
    - install-epel

- name: Install Nginx
  package:
    name: nginx
    state: latest
  tags:
    - install-nginx

- name: Enable nginx
  service:
    name: nginx
    enabled: true

- name: Start nginx
  shell: /usr/sbin/nginx &
